# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplemooc', '0005_auto_20160816_0854'),
        ('accounts', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(to='simplemooc.Course'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
