# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160816_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.ManyToManyField(blank=True, to='simplemooc.Course'),
        ),
    ]
