# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simplemooc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descri\xe7\xe3o')),
                ('program', models.TextField(blank=True, verbose_name='Programa\xe7\xe3o')),
                ('qtd_available', models.IntegerField(verbose_name='Vagas')),
                ('qtd_students', models.IntegerField(verbose_name='Alunos_matriculados')),
                ('begin_matric', models.DateField(blank=True, null=True, verbose_name='Inicio_inscri\xe7\xf5es')),
                ('end_matric', models.DateField(blank=True, null=True, verbose_name='Fim_inscri\xe7\xf5es')),
                ('begin_course', models.DateField(blank=True, null=True, verbose_name='Inicio_curso')),
                ('end_course', models.DateField(blank=True, null=True, verbose_name='Fim_curso')),
                ('image', models.ImageField(blank=True, null=True, upload_to=simplemooc.models.upload_location, verbose_name='Foto')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('keywords', models.CharField(blank=True, max_length=100, verbose_name='Palavras_chave')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplemooc.Category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('description', models.TextField(blank=True, verbose_name='Descri\xe7\xe3o')),
                ('material', models.FileField(blank=True, null=True, upload_to='materials_course/', verbose_name='Material')),
                ('activities', models.FileField(blank=True, null=True, upload_to='activities_course/', verbose_name='Atividades')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Vis\xedvel')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplemooc.Teacher', verbose_name='professor'),
        ),
    ]
