# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplemooc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='simplemooc.Category', verbose_name='categoria'),
        ),
    ]
