# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplemooc', '0003_auto_20160721_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='simplemooc.Modules', verbose_name='Modulos'),
        ),
    ]
